Resources:
  CityAppDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        -  AttributeName: Id
           AttributeType: S
        -  AttributeName: Category
           AttributeType: S
        -  AttributeName: UserId
           AttributeType: S
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: true
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH
        - AttributeName: Category
          KeyType: RANGE
      LocalSecondaryIndexes: 
        - IndexName:  NameIndex
          KeySchema:
            - AttributeName: Id
              KeyType: HASH
            - AttributeName: UserId
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
      TableName: CityAppDB
      Tags: 
        - Key: App
          Value: CityApp
      TimeToLiveSpecification: 
        AttributeName: TTL
        Enabled: true
